image: python:2.7
services:
    - mdillon/postgis:9.4
variables:
    POSTGRES_USER: "postgres"
    POSTGRES_PASSWORD: $POSTGRES_USER
    PGUSER: $POSTGRES_USER
    PGPASS: $POSTGRES_USER
    POSTGRES_DB: {{cookiecutter.app_name}}
    PGDATABASE: {{cookiecutter.app_name}}
    DB_HOST: "mdillon__postgis"
    DEPENDENCIES: "python-dev python-pip python-virtualenv git libpq-dev postgresql-server-dev-9.4 postgresql-client-9.4 libgdal1-dev libgeos-dev"
    TEST_APPS: ""
stages:
    - build
    - test
    - deploy
before_script:
    - apt-get update -qq && apt-get install -y -qq $DEPENDENCIES
    - virtualenv env
    - source env/bin/activate
    - pip install -r requirements.txt
test_django:
    stage: test
    script:
        - cd src/
        - ./manage.py test $TEST_APPS
